name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
    - name: Run tests
      run: cargo test --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
