name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose --manifest-path ./src-tauri/Cargo.toml --workspace

  doc:
    runs-on: ubuntu-latest
    if:  github.event_name == 'push' || github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - name: Run doc
      run: cargo doc --no-deps --manifest-path ./src-tauri/Cargo.toml --workspace --document-private-items

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src-tauri/target/doc/
