name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: sudo apt-get install libgtk-3-dev
    - name: Build
      run: cargo build --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
    - name: Run tests
      run: cargo test --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
