name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        target: x86_64-unknown-linux-gnu
        override: true
    - name: Build
      uses: actions-rs/cargo@v1
      with: 
        commands: build --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
    - name: Tests
      uses: actions-rs/cargo@v1
      with: 
        commands: test --verbose --manifest-path ./src-tauri/Cargo.toml --workspace
